R__LOAD_LIBRARY(libpodio.so)
R__LOAD_LIBRARY(libpodioRootIO.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4hep.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4hepDict.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4hepUtils.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4hepRDF.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4eic.so)
R__LOAD_LIBRARY(/opt/local/lib/libedm4eicDict.so)